Repository team-mariners/hungrydb, pull requests merged in 2020-04, with the labels that each got.

#124 Fix NavBar links issue
  app/controllers/api/v1/orders/orders_controller.rb
  app/javascript/components/managers/Index.js
  app/javascript/components/managers/ManageMenu.js
  app/javascript/components/managers/ManagePromo.js
  app/javascript/components/managers/common/NavigationBar.js
  app/javascript/components/managers/manageMenu/DeleteMenuSection.js
  app/javascript/components/managers/manageMenu/EditDish.js
  app/javascript/components/managers/manageMenu/EditMenuSection.js
  app/javascript/components/managers/manageMenu/NewDish.js
  app/javascript/components/managers/manageMenu/NewMenuSection.js
  app/javascript/components/managers/manageMenu/ToggleDish.js
  app/javascript/components/managers/managePromo/EditPromotion.js
  app/javascript/components/managers/managePromo/NewPromotion.js
Labels: bug fix, ready merge

#130 Display stats for completed orders only for managers
  app/controllers/api/v1/statistics/statistics_controller.rb
  app/javascript/components/managers/statistics/MonthSummary.js
Labels: ready merge

#108 Riders browsing info
  Gemfile.lock
  app/controllers/riders_controller.rb
  app/helpers/riders_helper.rb
  app/javascript/components/managers/OrdersStats.js
  app/javascript/components/riders/DashBoard.js
  app/javascript/components/riders/Index.js
  app/javascript/components/riders/SalarySummaryPage.js
  app/javascript/components/riders/common/RiderNaviBar.js
  app/javascript/components/riders/delivery/DeliveriesBoard.js
  app/javascript/components/riders/stats/SalarySummaryTable.js
  app/javascript/components/utilities/MonthPicker.js
  app/javascript/components/utilities/WeekPicker.js
  app/views/riders/index.html.erb
  config/routes.rb
  config/schedule.rb
  db/migrate/20200223103255_create_riders.rb
  db/migrate/20200330055226_create_full_time_riders.rb
  db/migrate/20200330055734_create_part_time_riders.rb
  db/migrate/20200404053904_create_update_order_status_trigger.rb
  db/migrate/20200405075210_create_rider_salaries.rb
  db/migrate/20200405083954_create_constants.rb
  db/migrate/20200405084535_create_on_delivery_complete_trigger.rb
  db/seeds.rb
  lib/tasks/database.rake
Labels: ready merge

#137 Update order and order modal
  app/controllers/api/v1/orders/orders_controller.rb
  app/controllers/riders_controller.rb
  app/javascript/components/managers/manageOrder/Order.js
  app/javascript/components/managers/manageOrder/OrderModal.js
  app/javascript/components/riders/delivery/Delivery.js
Labels: ready merge

#139 Add rider's work schedule page
  app/helpers/riders_helper.rb
  app/javascript/components/riders/Index.js
  app/javascript/components/riders/WorkSchedulePage.js
  app/javascript/components/riders/common/RiderNaviBar.js
  app/javascript/components/riders/delivery/DeliveriesBoard.js
  app/javascript/components/riders/schedule/WorkSchedule.js
  app/views/riders/schedule.html.erb
  config/routes.rb
Labels: ready merge

#145 Customer Front-end Touchup
  app/helpers/api/v1/orders/orders_helper.rb
  app/javascript/components/customers/cart/Cart.js
  app/javascript/components/customers/cart/CartItem.js
  app/javascript/components/customers/dashboard/LastOrder.js
  app/javascript/components/customers/orderhistory/OrderHistoryItem.js
  app/javascript/components/customers/orderhistory/OrderHistoryModal.js
  app/javascript/components/customers/ordersubmission/CompleteOrder.js
  app/javascript/components/customers/revieworder/Review.js
  app/javascript/components/managers/manageOrder/OrderModal.js
Labels: ready merge

#142 Complete Customer-FDS-Rider order and review flow
  app/controllers/api/v1/customer/customer_controller.rb
  app/controllers/customers_controller.rb
  app/controllers/order_controller.rb
  app/helpers/api/v1/orders/orders_helper.rb
  app/helpers/api/v1/restaurants/restaurants_helper.rb
  app/helpers/api/v1/reviews/reviews_helper.rb
  app/javascript/components/customers/CustomerIndex.js
  app/javascript/components/customers/dashboard/LastOrder.js
  app/javascript/components/customers/dashboard/LastReview.js
  app/javascript/components/customers/orderhistory/OrderHistory.js
  app/javascript/components/customers/ordersubmission/AddressBox.js
  app/javascript/components/customers/ordersubmission/CompleteOrder.js
  app/javascript/components/customers/readonlycart/ReadOnlyCart.js
  app/javascript/components/customers/readonlycart/ReadOnlyCartItem.js
  app/javascript/components/customers/readonlycart/ReadOnlyCartItemTable.js
  app/javascript/components/customers/readonlycart/ReadOnlyCartPointsDisplay.js
  app/javascript/components/customers/readonlycart/ReadOnlyCartPromoDisplay.js
  app/javascript/components/customers/revieworder/Review.js
  app/views/customers/order_in_progress.html.erb
  app/views/customers/review.html.erb
  config/routes.rb
  db/migrate/20200408091951_create_notify_customer_order_complete.rb
Labels: ready merge

#146 Add triggers and sql constraints to enforce work schedule constraints
  db/migrate/20200330055312_create_monthly_work_schedules.rb
  db/migrate/20200330055822_create_weekly_work_schedules.rb
  db/migrate/20200330055914_create_working_intervals.rb
  db/migrate/20200408013410_create_weekly_work_schedule_total_hours_trigger.rb
  db/migrate/20200408043331_create_check_full_time_rider_work_schedule_trigger.rb
  db/migrate/20200408084205_create_check_working_interval_not_overlap_trigger.rb
  db/migrate/20200408105511_create_check_one_hour_break_trigger.rb
  db/migrate/20200408133946_create_check_consecutive_work_days_trigger.rb
  db/seeds.rb
Labels: ready merge

#149 Loosen the restriction of work schedules triggers
  db/migrate/20200408013410_create_weekly_work_schedule_total_hours_trigger.rb
  db/migrate/20200408043331_create_check_full_time_rider_work_schedule_trigger.rb
  db/migrate/20200408105511_create_check_one_hour_break_trigger.rb
  db/migrate/20200408133946_create_check_consecutive_work_days_trigger.rb
  db/seeds.rb
Labels: ready merge

#150 Fix failing triggers
  db/migrate/20200408013410_create_weekly_work_schedule_total_hours_trigger.rb
  db/migrate/20200408043331_create_check_full_time_rider_work_schedule_trigger.rb
  db/migrate/20200408105511_create_check_one_hour_break_trigger.rb
  db/migrate/20200408133946_create_check_consecutive_work_days_trigger.rb
Labels: bug fix

#148 Fix faulty code and reduce order progress page lag
  app/controllers/customers_controller.rb
  app/controllers/order_controller.rb
  app/javascript/components/customers/readonlycart/ReadOnlyCart.js
  db/migrate/20200408091951_create_notify_customer_order_complete.rb
Labels: ready merge

#153 Fix bug in trigger
  db/migrate/20200408043331_create_check_full_time_rider_work_schedule_trigger.rb
Labels: bug fix, ready merge

#152 Add project set up guide
  README.md
Labels: documentation, ready merge

#154 Fix bug in trigger
  db/migrate/20200408105511_create_check_one_hour_break_trigger.rb
Labels: bug fix, ready merge

#157 Fix bug in check one hour break trigger
  db/migrate/20200408105511_create_check_one_hour_break_trigger.rb
Labels: bug fix, ready merge

#156 Fix bug when a restaurant doesn't have any orders
  app/controllers/api/v1/orders/orders_controller.rb
  app/javascript/components/managers/manageOrder/OrdersBoard.js
Labels: bug fix, ready merge

#155 Implement Search functions, Fix bugs & Enhance/Complete UI
  app/assets/stylesheets/menu.scss
  app/controllers/home_controller.rb
  app/controllers/order_controller.rb
  app/helpers/api/v1/customer/customer_helper.rb
  app/javascript/components/customers/CustomerIndex.js
  app/javascript/components/customers/cart/Cart.js
  app/javascript/components/customers/dashboard/LastOrder.js
  app/javascript/components/customers/order/Menu.js
  app/javascript/components/customers/order/Restaurants.js
  app/javascript/components/customers/orderhistory/OrderHistory.js
  app/javascript/components/customers/promotions/PromosPage.js
  app/javascript/components/customers/reviews/ReviewHistory.js
  app/javascript/components/customers/reviews/ReviewItem.js
  app/javascript/components/homepage/Home.js
  app/javascript/components/homepage/HomeContainer.js
  app/javascript/components/homepage/HomePromosCard.js
  app/views/home/promotions.html.erb
  config/routes.rb
Labels: ready merge

#159 Create users total participation trigger
  db/migrate/20200215165756_devise_create_users.rb
  db/migrate/20200223103005_create_admins.rb
  db/migrate/20200223103016_create_managers.rb
  db/migrate/20200223103255_create_riders.rb
  db/migrate/20200223110049_create_customers.rb
  db/migrate/20200409103140_create_users_total_participation_trigger.rb
  db/seeds.rb
Labels: ready merge

#160 Delete users total participation trigger
  db/migrate/20200409103140_create_users_total_participation_trigger.rb
Labels: ready merge

#161 Disable core services when it's not operating hours
  app/javascript/components/customers/CustomerNavBar.js
  app/javascript/components/helpers/Helpers.js
  app/javascript/components/riders/delivery/Delivery.js
Labels: ready merge
